# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6744495d648ee2b0142006c28d5dbb6bafe4c299d8750540d9317defdd9933f2e454ebe6a7d01212a3a1bfbf1a1829777a0af05a5814bcb82302f253f9137648

test:
  secret_key_base: 242ae1f8f88ee4bc8187fab37a2eb7b173126d99c2249a6cc803bbde71dbe99c347140356c1a9f851293f7f35fa920cdb86af55527d3cd73271b6b38a3986b4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
