source 'https://rubygems.org'

#core libraries
gem 'rails', '4.2.3'
gem 'sqlite3'

#frontend tools
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'bootstrap-sass', '~>3.3.5'
gem 'simple_form'
gem 'jquery-rails'

#other
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'annotate'

end
